### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by makamekm** [retifrav/glfw-imgui-example#1]
There is no instruction of how to build it, so I tried cmake.
```
% cmake .
Project name: glfw-imgui
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLFW
    linked by target "glfw-imgui" in directory ./

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

c++ is the worst PL ever.

**Comment by retifrav** [comment]
What doesn't work, which post this comment is for, use the issue that is linked in the post.

**Comment by retifrav** [comment]
> There is no instruction

The `README.md` contains a link to the [detailed article](https://retifrav.github.io/blog/2019/08/04/glfw-dear-imgui/).

> C++ is the worst PL ever

Is it now.
